name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_BASE: jstz-dev

jobs:
  build-docker:
    name: Build and push Docker images
    strategy:
      matrix:
        include:
          - image: riscv64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: '${{ env.DOCKER_REGISTRY }}'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: >-
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}/hermit-toolchain-${{ matrix.image }}
          tags: |
            type=ref,event=tag
            {{date 'YYYYMMDD'}}
      - uses: docker/build-push-action@v6.3.0
        with:
          context: .
          push: true
          build-args: |
            TARGET=${{ matrix.image }}-hermit
          cache-from: type=gha
          cache-to: 'type=gha,mode=max'
          tags: '${{ steps.meta.outputs.tags }}'
          labels: '${{ steps.meta.outputs.labels }}'
